---
external-ips:
    dynamic-ips: true
#   service-ip: 172.29.0.1
#   ips:
#      - 172.29.0.2
#      - 172.29.0.3
#      - 172.29.0.4
cluster:
   labels:
      app: infinispan-server
   ports:
      - 11222